---

dist: xenial
services:
  - xvfb

before_install:
  # Debian has since stretch an OCR-B font and a fonts-ocr-a
  # Xenial (Ubuntu en general?) only has fonts-ocr-a
  - sudo apt-get install -y libreoffice-writer fonts-ocr-a poppler-utils

script: tests/odt_2_pdf.sh

notifications:
  email:
  - niklaus.giger@member.fsf.org

